module.exports = {
    "adware": "广告",
    "android malware": "安卓恶意程序",
    "apt": "APT攻击",
    "backdoor": "远控木马",
    "banker": "网银大盗",
    "bitcoin": "比特币节点",
    "bogons": "未启用IP",
    "botnet cc": "僵尸网络 C2",
    "bots": "僵尸主机",
    "bruteforce": "爆破攻击",
    "coinminer": "挖矿",
    "ddos": "DDOS攻击",
    "dga": "DGA域名",
    "dynamic ip": "动态IP",
    "downloader": "木马下载器",
    "exploit": "漏洞利用",
    "frauds": "欺诈",
    "gambling": "赌博",
    "hacktool": "黑客工具",
    "hooligan": "流氓软件",
    "ios malware": "IOS恶意软件",
    "iot attack c2": "IoT攻击 C2",
    "iot bots": "IoT失陷主机",
    "keylogger": "键盘记录器",
    "macro": "宏病毒",
    "mac malware": "MAC恶意软件",
    "malscript": "恶意脚本",
    "malssl": "恶意SSL证书",
    "malware": "恶意软件",
    "malweb": "恶意网站",
    "phishing": "钓鱼",
    "porn": "色情网站",
    "private": "私有地址",
    "proxy": "代理节点",
    "ransomware": "勒索软件",
    "scanning": "主机扫描",
    "sinkhole c2": "Sinkhole C2",
    "spam": "垃圾邮件",
    "spider": "网络爬虫",
    "spyware": "间谍软件",
    "stealer": "窃密木马",
    "suspicious": "可疑",
    "tor": "Tor节点",
    "trojan c2": "木马回连服务器",
    "trojan downloader c2": "木马下载服务器",
    "virus": "感染型病毒",
    "voip attack": "voip攻击",
    "webvulattack": "Web漏洞攻击",
    "worm": "网络蠕虫",
    "sinkhole redirect ip": "Sinkhole重定向IP",
    "attachment": "可疑邮件附件",
    "freewebhosts": "免费网络主机",
    "ole-control": "内嵌OLE",
    "ole-autolin": "内嵌OLE",
    "ole-embedded": "内嵌OLE",
    "dde exploit": "dde漏洞",
    "honeypot": "蜜罐",
    "whitelist": "白名单",
    "att": "可疑邮件附件",
    "microsoft": "微软",
    "alexa": "alexa",
    "evader": "逃逸者",
    "abc": "美国广播公司",
    "abortion": "流产",
    "drugs": "毒品",
    "academic": "学术",
    "access_providers": "接入提供商",
    "accountants": "会计",
    "acer": "宏基",
    "plugins": "插件",
    "address_phone": "地址电话",
    "adult content": "成人内容",
    "adventure_quest": "冒险任务",
    "advice": "建议",
    "advisories_and_patches": "公告补丁",
    "advocacy groups": "倡导",
    "affiliate_networks": "分支机构",
    "agences_conseil": "咨询机构",
    "agencies": "办事处",
    "alcohol_tobacco": "烟酒",
    "alternative_monetary": "替代货币",
    "android": "安卓",
    "animation": "动画",
    "antibodies": "抗体",
    "antivirus": "杀毒软件",
    "im": "即时通讯",
    "apache": "Apache软件",
    "appliances": "应用",
    "app_download": "下载站",
    "application_layer_gateways": "网关",
    "army": "军事",
    "arts": "艺术",
    "asia": "亚洲",
    "ask": "问答",
    "associations": "协会",
    "auctions": "拍卖",
    "audio": "音频",
    "australia": "澳大利亚",
    "authentication": "认证",
    "automotive": "汽车",
    "autoresponder": "聊天机器人",
    "bancos": "银行",
    "bandwidth_tests": "带宽测试",
    "bbc": "BBC",
    "belgium": "比利时",
    "berkeley": "伯克利",
    "bing": "必应",
    "bittorrent": "种子",
    "blender": "搅拌机",
    "blizzard_entertainment": "暴雪娱乐公司",
    "blogger": "博客",
    "bmw": "宝马",
    "bois_et_papier": "木材造纸",
    "bonusprogramme": "奖金计划",
    "bookmakers": "博彩公司",
    "books": "书籍",
    "boston_university": "波士顿大学",
    "boulder": "科罗拉多大学",
    "breaking_news": "即时新闻",
    "bricolage": "拼装",
    "brigham_young_university": "杨百翰大学",
    "broadcasters": "广播",
    "brokerages": "券商",
    "brokerages trading": "券商交易",
    "browsers": "浏览器",
    "bullion": "金条",
    "business": "商业",
    "business_economy": "商业金融",
    "cable": "电缆",
    "cache_tools": "缓存工具",
    "cad": "CAD",
    "calibration": "校准",
    "california": "加州",
    "canada": "加拿大",
    "car_rentals": "汽车出租",
    "carriers": "运营商",
    "cartography": "制图",
    "case_western_reserve_university": "西方预备大学",
    "casualgames": "休闲游戏",
    "cd": "CD",
    "central_banks": "中央银行",
    "central_michigan_university": "中央密歇根大学",
    "cgi_proxy": "CGI代理",
    "charlotte": "夏洛特",
    "chat instant messaging": "聊天通信",
    "chats": "聊天",
    "forums": "论坛",
    "cheats": "欺骗",
    "chulalongkorn_university": "朱拉隆功大学",
    "cisco": "思科",
    "clarkson_university": "克拉克森大学",
    "clients": "客户",
    "clothing": "服装",
    "coding": "编码",
    "collaboration": "协作",
    "collections": "集合",
    "college": "大专院校",
    "colorado": "科罗拉多州",
    "commerce_industry": "工商业",
    "companies": "公司",
    "complaints": "投诉",
    "components": "组件",
    "computer security": "计算机安全",
    "computer_aided_translation": "在线翻译",
    "computergames": "计算机游戏",
    "computers": "计算机",
    "computers internet": "互联网",
    "computersandsoftware": "计算机软件",
    "confectionery": "糖果",
    "conferencing": "会议",
    "consulting": "咨询",
    "consumer_opinion": "消费者意见",
    "containers": "容器",
    "content": "内容",
    "content delivery networks": "内容交付网络",
    "content_management": "内容管理",
    "converters": "转换器",
    "cookies": "cookies",
    "counters_and_trackers": "跟踪器",
    "coupons": "优惠券",
    "cpus": "CPU",
    "credit_cards": "信用卡",
    "credit_reports": "信用报告",
    "creighton_university": "克里顿大学",
    "crime_and_justice": "犯罪与司法",
    "cultural institutions": "文化机构",
    "cuny": "纽约市立大学",
    "current_time": "时间",
    "czech_republic": "捷克共和国",
    "data_compression": "数据压缩",
    "data_formats": "数据格式",
    "data_recovery": "数据恢复",
    "databases": "数据库",
    "debian": "debian",
    "delivery_and_management_systems": "交付管理系统",
    "departments_and_agencies": "部门机构",
    "desktop_applications": "桌面应用",
    "desktop_customization": "桌面定制",
    "desktop_readers": "桌面阅读器",
    "detection_and_removal_tools": "检测工具",
    "deutschland": "五金",
    "developers": "开发商",
    "developers_and_publishers": "开发商",
    "development_tools": "开发工具",
    "diagnostics": "诊断",
    "digital": "数字化",
    "digital_audio_workstations": "音频工作站",
    "digital_video": "数字视频",
    "distribution_systems": "分销系统",
    "dj": "DJ",
    "doctors": "医生",
    "download": "下载",
    "drexel_university": "德雷克塞尔大学",
    "duke_university": "杜克大学",
    "dynamic content": "动态内容",
    "dynamic dns": "动态域名",
    "e-greetings": "电子贺卡",
    "email": "电子邮件",
    "e-payment": "电子支付",
    "editors": "编者",
    "education": "教育",
    "educational institutions": "教育机构",
    "educational materials": "教材",
    "educational video": "教育视频",
    "egypt": "埃及",
    "elections": "选举",
    "electronic_arts": "电子艺术",
    "electronic_cash": "电子现金",
    "electronics": "电子产品",
    "electronics_and_electrical": "电子电气",
    "embedded": "嵌入式",
    "emerging exploits": "新兴的利用",
    "engineering": "工程",
    "english": "英语",
    "entertainment": "娱乐",
    "entertainment video": "娱乐视频",
    "equipment": "设备",
    "equipment_and_software": "设备软件",
    "error_checking_and_repair": "错误检查修复",
    "eth_zurich": "苏黎世",
    "european_union": "欧盟",
    "exchanges": "交流",
    "extensions_and_templates": "扩展模板",
    "extraction_and_transformation": "提取转换",
    "faqs": "问题解答",
    "file download servers": "文件下载服务器",
    "filesharing": "文件共享",
    "filtering": "滤波",
    "financial": "金融",
    "financial data and services": "财务",
    "financial services": "金融服务",
    "firebug": "firebug",
    "florida": "佛罗里达",
    "florida_institute_of_technology": "佛罗里达理工学院",
    "for kids": "儿童",
    "form_data": "表单数据",
    "france": "法国",
    "fraud": "欺诈",
    "free": "免费",
    "free_web_space_providers": "网盘",
    "freeware": "免费软件",
    "friedrich-alexander_university_erlangen-nuremberg": "埃尔朗根-纽伦堡大学",
    "ftp": "FTP",
    "galleries": "画廊",
    "games": "游戏",
    "gas_and_electricity": "电力",
    "gay or lesbian or bisexual interest": "同性恋",
    "gemstones": "宝石",
    "generators": "发电机",
    "georgia_state_university": "格鲁吉亚州立大学",
    "git": "Git",
    "gnome": "Gnome",
    "google": "谷歌",
    "gov": "政府网站",
    "grand_theft_auto": "侠盗飞车",
    "graphics_chip_vendors": "图形芯片供应商",
    "guides": "导游",
    "guides_and_directories": "指南",
    "hacking": "黑客",
    "hard_disk_encryption": "硬盘加密",
    "hardware": "硬件",
    "harvard_university": "哈佛大学",
    "hate": "厌恶",
    "health": "健康",
    "hobbies": "爱好",
    "holding_companies": "控股公司",
    "home_improvement": "家装",
    "hosted business applications": "托管业务应用程序",
    "hosted_components_and_services": "托管组件",
    "hosted_services": "托管服务",
    "hosting": "托管",
    "hosts": "主机",
    "humor": "幽默",
    "icons": "图标",
    "icq": "ICQ",
    "id_cards_and_systems": "身份系统",
    "illegal": "非法",
    "illegal drugs": "非法毒品",
    "illegal or questionable": "非法或可疑的",
    "illegal questionable": "非法可疑",
    "image_cataloguing": "图片",
    "image_generation": "图片生成",
    "image_hosting": "图片托管",
    "independent_tech_support": "技术支持",
    "india": "印度",
    "indianapolis": "印第安纳波利斯",
    "individual_tax": "个人税",
    "industry_analysts": "行业分析师",
    "infiniti": "英菲尼迪",
    "information technology": "信息技术",
    "information_services": "信息服务",
    "institutions": "机构",
    "insurance": "保险",
    "integrated_circuits": "集成电路",
    "international_broadcasters": "国际广播公司",
    "internet auctions": "互联网拍卖",
    "internet infrastructure": "网络基础设施",
    "internet tv": "互联网电视",
    "internet telephony": "互联网电话",
    "internet_backbone": "互联网骨干",
    "internet_traffic": "互联网流量",
    "internetmarketing": "网络营销",
    "intimate apparel swimsuit": "内衣",
    "investment_banks": "投资银行",
    "ipod": "iPod",
    "issuers": "发行人",
    "italy": "意大利",
    "jakarta": "雅加达",
    "james_madison_university": "詹姆斯麦迪逊大学",
    "javascript": "JavaScript",
    "job search": "求职",
    "joke program": "整人程序",
    "jquery": "jQuery",
    "keyboards": "键盘",
    "lancaster_university": "兰卡斯特大学",
    "langues": "语言",
    "library_and_information_science": "图书馆",
    "libreoffice": "办公",
    "lifestyle": "生活方式",
    "linear": "Linear",
    "lingerie and swimsuit": "内衣泳装",
    "live-shows": "演艺",
    "live_support": "现场支持",
    "load_balancing": "负载均衡",
    "location_and_tracking": "位置追踪",
    "london_school_of_economics_and_political_science": "伦敦经济学院",
    "macintosh": "苹果电脑",
    "ad_alliance": "广告联盟",
    "magazines": "杂志",
    "magazines_and_e-zines": "电子杂志",
    "major_retailers": "零售商",
    "malaysia": "马来西亚",
    "malware accomplice": "恶意组织",
    "manufacturers": "制造商",
    "manufacturing": "制造业",
    "marijuana": "大麻",
    "market_research": "市场调查",
    "marketing": "营销",
    "markets": "市场",
    "marvel": "漫威",
    "massachusetts_institute_of_technology": "麻省理工学院",
    "massive_multiplayer_online": "在线游戏",
    "mato_grosso": "马托格罗索",
    "mechanical_design": "机械设计",
    "media file download": "媒体",
    "medical_records": "病历",
    "medical_transcription": "医疗转录",
    "members": "会员",
    "memory": "内存",
    "merchant_services": "商家服务",
    "message boards and forums": "论坛",
    "message_boards": "留言板",
    "search": "搜索",
    "mexico": "墨西哥",
    "michigan_state_university": "密歇根州立大学",
    "microsoft_corporation": "微软公司",
    "middle_tennessee_state_university": "中田纳西州立大学",
    "ministry_of_foreign_affairs": "外交部",
    "mobile malware": "手机恶意软件",
    "models": "模特",
    "mohawk_college": "莫霍克学院",
    "money_transfers": "汇款",
    "monitoring": "监控",
    "search_engines": "搜索引擎",
    "motherboards": "主板",
    "mozilla": "Mozilla",
    "ms_office": "微软Office",
    "music": "音乐",
    "myspace": "MySpace",
    "mysql": "MySql",
    "national_electrical_code": "电气",
    "national_tsing_hua_university": "清华大学",
    "netware": "网络软件",
    "network": "网络",
    "network_management": "网络管理",
    "networking": "联网",
    "netzbetreiber": "网络运营商",
    "new_york": "纽约",
    "newly registered websites": "新注册网站",
    "news": "新闻媒体",
    "newsgroups": "新闻",
    "node": "节点",
    "non-traditional religions": "非传统宗教",
    "nonprofit_resources": "非营利资源",
    "north_america": "北美",
    "northern_arizona_university": "北亚利桑那大学",
    "northern_michigan_university": "北密歇根大学",
    "not recommended site": "不推荐的网站",
    "nudity": "裸露",
    "nutrition": "营养",
    "oakland_university": "奥克兰大学",
    "obscene language": "淫秽语言",
    "office_products": "办公用品",
    "ohio_state_university": "俄亥俄州立大学",
    "online": "在线",
    "online brokerage and trading": "网上交易",
    "online_cardrooms": "在线棋牌",
    "online_magazines": "在线杂志",
    "online_media": "在线媒体",
    "online_tools": "在线工具",
    "onlinedating": "在线约会",
    "onlinegames": "线上游戏",
    "onlinepay": "在线支付",
    "onlinephotos": "在线照片",
    "onlineshop": "网上商店",
    "open_source": "开源软件",
    "openoffice": "Office",
    "openstreetmap": "开源地图",
    "oracle": "甲骨文",
    "oracle_corporation": "甲骨文公司",
    "oregon_state_university": "俄勒冈州立大学",
    "org": "组织",
    "organization_of_american_states": "美国各州的组织",
    "organizational email": "组织邮件",
    "outsourcing": "外包",
    "pace_university": "佩斯大学",
    "parks": "公园",
    "password cracking": "密码破解",
    "password_recovery": "密码恢复",
    "pay to surf": "支付网站",
    "pay": "支付系统",
    "p2p": "P2P",
    "file sharing": "P2P文件共享",
    "perfect_world_entertainment": "完美世界",
    "network storage": "个人存储",
    "personal sites": "个人首页",
    "personal_finance": "个人财务",
    "personal_firewalls": "个人防火墙",
    "personal_pages": "个人页面",
    "personalization": "个性化",
    "personals": "交友",
    "personals and dating": "约会",
    "photo searches": "图片搜索",
    "photo_sharing": "图片共享",
    "photography": "摄影",
    "php": "PHP",
    "planck": "普朗克",
    "player_rankings_and_cheatsheets": "玩家排名",
    "players": "玩家",
    "poker": "扑克",
    "political organizations": "政治组织",
    "politics": "政治",
    "polls_and_surveys": "民意调查",
    "portals": "门户网站",
    "postal_services": "邮政服务",
    "potentially damaging content": "潜在破坏内容",
    "potentially exploited documents": "潜在漏洞文档",
    "potentially malicious software": "潜在恶意软件",
    "premium": "溢价",
    "prescribed medications": "处方药",
    "presentation": "介绍",
    "presentation_sharing": "演示分享",
    "pro_evolution_soccer": "足球",
    "products": "制品",
    "products_and_tools": "生产工具",
    "professional and worker organizations": "工人组织",
    "professional_golfers": "高尔夫",
    "project_hosting": "项目托管",
    "promotion": "促销",
    "provider": "提供商",
    "proxy avoidance": "代理",
    "public_domain": "公共区域",
    "publications": "出版物",
    "publishers": "出版商",
    "purdue_university": "普渡大学",
    "python": "Python",
    "quotes": "报价",
    "radio": "无线电",
    "radiomusic": "广播音乐",
    "rails": "框架",
    "real estate": "房地产",
    "recreation hobbies": "爱好娱乐",
    "red_hat": "红帽",
    "social networks": "社交网络",
    "redirects": "重定向",
    "reference": "参考",
    "reference materials": "参考资料",
    "reference_tools": "参考工具",
    "religion": "宗教",
    "remote access program": "远程",
    "remote_access": "远程控制",
    "republican_party": "共和党",
    "research": "研究分析",
    "resource": "资源",
    "response_tools": "响应工具",
    "ressourcen_und_tools": "资源工具",
    "resources": "资源",
    "restaurants and dining": "餐馆",
    "restaurants food": "餐馆",
    "retail": "零售",
    "reviews": "评论",
    "ringtones mobilephone downloads": "手机铃声下载",
    "rochester_institute_of_technology": "罗切斯特理工学院",
    "rockstar_games": "摇滚游戏",
    "royalty_free": "免版税",
    "saas": "萨斯",
    "san_francisco": "旧金山",
    "screenplay_editors": "剧本编辑",
    "scripting": "脚本",
    "moteurs_de_recherche": "搜索引擎",
    "security_scanning": "安全扫描",
    "publishing": "出版社",
    "semiconductors": "半导体",
    "service and philanthropic organizations": "慈善组织",
    "service_companies": "服务公司",
    "service_providers": "服务提供商",
    "services": "服务",
    "shareware": "共享软件",
    "shell": "shell",
    "shopping": "购物",
    "slovenia": "斯洛文尼亚",
    "sniping": "秒杀",
    "organizations": "社会组织",
    "facebook": "脸书",
    "linkedin": "领英",
    "twitter": "推特",
    "youtube": "Youtube",
    "society lifestyle": "生活方式",
    "software": "软件",
    "software downloads": "软件下载",
    "software_development": "软件开发",
    "solutions_professionnelles": "专业解决方案",
    "sony": "索尼",
    "south_africa": "南非",
    "south_korea": "韩国",
    "spam_filtering": "垃圾邮件过滤",
    "special events": "特别活动",
    "spelling_and_grammar": "拼写语法",
    "sport hunting and gun clubs": "水下狩猎",
    "sports": "体育",
    "spyware_and_adware": "间谍广告",
    "sqlite": "Sqlite",
    "standards": "标准",
    "stanford_university": "斯坦福大学",
    "storage": "存储",
    "streaming": "流媒体",
    "sublime_text": "Sublime",
    "subscription-free_services": "免费订阅服务",
    "sun_microsystems": "Sun",
    "suspicious content": "可疑内容",
    "suspicious embedded link": "可疑链接",
    "switzerland": "瑞士",
    "system": "系统",
    "tabloids": "小报",
    "taxation": "税收",
    "technical_university_of_berlin": "柏林技术大学",
    "technology_vendors": "技术供应商",
    "telecommunicaties": "远程通信",
    "telecommunications": "电信",
    "telecomunicaciones": "电信公司",
    "telephony": "电话",
    "temporary_addresses": "临时地址",
    "terrorism": "恐怖主义",
    "test_and_measurement": "测量",
    "testing_and_evaluation": "评估",
    "texas_state_university": "得克萨斯州立大学",
    "text and media messaging": "文本媒体消息",
    "the_gimp": "GUN",
    "themes": "主题",
    "thin_clients": "数据交付",
    "third_party_certificate_authorities": "第三方认证机构",
    "tokyo": "东京",
    "toolbars": "工具栏",
    "tools": "工具",
    "tools_and_equipment": "工具设备",
    "tracking": "追踪",
    "translators cached pages": "翻译",
    "travel": "旅游",
    "tufts_university": "簇夫大学",
    "ubisoft_entertainment": "育碧娱乐",
    "unauthorized mobile marketplaces": "未经授权的移动市场",
    "unicode": "unicode",
    "united_nations": "联合国",
    "united_states": "美国",
    "universidad_de_granada": "格拉纳达大学",
    "universiteit_twente": "特温特大学",
    "college_park": "大学",
    "university_centers_and_colleges": "石溪大学",
    "university_of_akron": "阿克伦大学",
    "university_of_british_columbia": "不列颠哥伦比亚大学",
    "university_of_calgary": "卡尔加里大学",
    "university_of_delaware": "特拉华大学",
    "university_of_florida": "佛罗里达大学",
    "university_of_hawaii": "夏威夷大学",
    "university_of_indonesia": "印度尼西亚大学",
    "university_of_limerick": "利默里克大学",
    "university_of_mississippi": "密西西比大学",
    "university_of_pennsylvania": "宾夕法尼亚大学",
    "university_of_southampton": "南安普敦大学",
    "university_of_virginia": "弗吉尼亚大学",
    "university_of_washington": "华盛顿大学",
    "university_of_western_australia": "西澳大学",
    "unknown": "未知",
    "url-shortening": "短网址",
    "url_encoded": "网址编码",
    "utah": "犹他州",
    "utilities": "公用事业",
    "variety": "品种",
    "video": "视频",
    "video_games": "视频游戏",
    "video_sharing": "视频共享",
    "viewers": "查看器",
    "violence": "暴力",
    "violence hate racism": "暴力与种族主义",
    "virtual_managers": "虚拟经理",
    "virtual_network_computing": "虚拟网络计算",
    "vmware": "Vmware",
    "voip": "网络电话",
    "volunteer_focus_groups": "志愿者组织",
    "wallets": "钱包",
    "washington": "华盛顿",
    "watercraft": "船舶",
    "weapons": "武器",
    "weather": "天气",
    "web": "Web",
    "web advertisement": "网络广告",
    "web analytics": "网站分析",
    "web and email marketing": "电子邮件",
    "web chat": "在线聊天",
    "web collaboration": "网络协作",
    "web hosting": "虚拟主机",
    "web images": "网页图像",
    "web infrastructure": "Web基础设施",
    "web_applications": "web应用程序",
    "web_based": "基于网络",
    "web_design_and_development": "网页设计",
    "web_tools": "网络工具",
    "webmail": "网络邮件",
    "webproxy": "网页代理",
    "website_promotion": "网站推广",
    "weight_loss": "减肥",
    "wholesale_and_distribution": "批发",
    "wikipedia": "维基百科",
    "williams_college": "威廉姆斯学院",
    "windows": "windows",
    "windows_tools_and_drivers": "Windows工具",
    "wireless": "无线",
    "wireless_data": "无线数据",
    "wireless_phones": "无线电话",
    "wordpress": "wordpress",
    "yonsei_university": "延世大学",
    "edu": "教育",
    "webmaster": "站长",
    "web_game": "网页游戏",
    "tv": "电视台",
    "lottery": "彩票",
    "live": "直播",
    "dns": "域名服务器",
    "phone": "手机",
    "network_monitor": "网络监控",
    "classify": "分类",
    "wallpaper": "桌面壁纸",
    "ankara_university": "安卡拉大学",
    "guangdong": "广东",
    "stocks_bonds": "股票债券",
    "phinshing": "钓鱼",
    "script": "脚本",
    "transport": "运输",
    "words": "文字处理",
    "qq": "腾讯qq",
    "job": "就业",
    "culture": "文化",
    "network_provider": "网络供应商",
    "strategy": "攻略",
    "bbs": "bbs",
    "novel": "小说阅读",
    "test-file": "测试文件",
    "newspaper": "报纸",
    "design": "设备器具",
    "database": "数据库",
    "blog": "博客",
    "national_taiwan_university": "国立台湾大学",
    "host": "托管商",
    "national_central_university": "国立中央大学",
    "podcast": "播客",
    "film": "电影",
    "security_company": "网络安全公司",
    "xbox": "Xbox",
    "idc": "IDC服务器",
    "bidding": "竞价排名",
    "sign": "数字证书",
    "sms-flooder": "短信轰炸",
    "packed": "加壳程序",
    "flooder": "洪水攻击",
    "iot malware": "IoT恶意软件",
    "dropper": "木马释放器",
    "campaign": "黑产团伙",
    "compromise site": "挂马网站",
    "riskware": "风险软件",
    "rogue dns": "恶意DNS服务器",
    "trojan": "木马",
    "c2": "C2"
}
